"""create table

Revision ID: e20b5c37905e
Revises: 
Create Date: 2023-07-27 11:46:28.053998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20b5c37905e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_code',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False, comment='コードID'),
    sa.Column('ckind', sa.Integer(), nullable=False, comment='種別'),
    sa.Column('chead', sa.String(length=10), nullable=False, comment='ヘッダ'),
    sa.Column('cenumber', sa.String(length=5), nullable=False, comment='英番号'),
    sa.Column('cnumber', sa.Integer(), nullable=False, comment='通番号'),
    sa.Column('cfoot', sa.String(length=10), nullable=False, comment='フッダー'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('m_code_template',
    sa.Column('ctid', sa.Integer(), autoincrement=True, nullable=False, comment='テンプレートID'),
    sa.Column('ctkind', sa.Integer(), nullable=False, comment='種別'),
    sa.Column('cthead', sa.VARCHAR(length=10), nullable=False, comment='ヘッダ'),
    sa.Column('ctenumber', sa.VARCHAR(length=5), nullable=False, comment='英番号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('ctid')
    )
    op.create_table('m_parts',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False, comment='パーツID'),
    sa.Column('pcid', sa.Integer(), nullable=False, comment='cidの外部キー'),
    sa.Column('pcd', sa.VARCHAR(length=256), nullable=False, comment='パーツコード'),
    sa.Column('pname', sa.VARCHAR(length=256), nullable=False, comment='パーツ名'),
    sa.Column('ppname', sa.VARCHAR(length=256), nullable=False, comment='パーツ一般名'),
    sa.Column('prevision', sa.VARCHAR(length=256), nullable=False, comment='リビジョン'),
    sa.Column('pvendor', sa.VARCHAR(length=256), nullable=False, comment='取引先コード'),
    sa.Column('ptype', sa.VARCHAR(length=256), nullable=False, comment='型式'),
    sa.Column('pmaterial', sa.VARCHAR(length=256), nullable=False, comment='材料名'),
    sa.Column('pio', sa.VARCHAR(length=256), nullable=False, comment='内外策'),
    sa.Column('pstatus', sa.Integer(), nullable=False, comment='ステータス'),
    sa.Column('pmtlmain_cost', sa.Integer(), nullable=False, comment='主要材料コスト'),
    sa.Column('pmtlsub_cost', sa.Integer(), nullable=False, comment='補助材料コスト'),
    sa.Column('pprocdict_cost', sa.Integer(), nullable=False, comment='外注加工費'),
    sa.Column('pprocsub_cost', sa.Integer(), nullable=False, comment='直接労務費'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('m_staff',
    sa.Column('scode', sa.Integer(), autoincrement=True, nullable=False, comment='社員番号'),
    sa.Column('sname1', sa.VARCHAR(length=256), nullable=False, comment='氏'),
    sa.Column('sname2', sa.VARCHAR(length=256), nullable=False, comment='字'),
    sa.Column('sname3', sa.VARCHAR(length=256), nullable=False, comment='氏（カナ）'),
    sa.Column('sname4', sa.VARCHAR(length=256), nullable=False, comment='字（カナ）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('scode')
    )
    op.create_table('m_tori',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False, comment='取引先ID'),
    sa.Column('tname1', sa.VARCHAR(length=256), nullable=False, comment='取引先名'),
    sa.Column('tname2', sa.VARCHAR(length=256), nullable=False, comment='取引先名（カナ）'),
    sa.Column('zipcode', sa.VARCHAR(length=64), nullable=False, comment='住所'),
    sa.Column('address1', sa.VARCHAR(length=256), nullable=False, comment='県'),
    sa.Column('address2', sa.VARCHAR(length=256), nullable=False, comment='市区町村'),
    sa.Column('address3', sa.VARCHAR(length=256), nullable=False, comment='番地'),
    sa.Column('address4', sa.VARCHAR(length=256), nullable=False, comment='アパート・ビル名'),
    sa.Column('tel1', sa.VARCHAR(length=64), nullable=False, comment='電話番号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('t_tree_table',
    sa.Column('tree_id', sa.VARCHAR(length=256), nullable=False, comment='ツリーID'),
    sa.Column('composition_id', sa.VARCHAR(length=256), nullable=False, comment='構成ID'),
    sa.Column('parts_id', sa.VARCHAR(length=256), nullable=False, comment='字'),
    sa.Column('lv', sa.VARCHAR(length=256), nullable=False, comment='氏（カナ）'),
    sa.Column('parent_id', sa.VARCHAR(length=256), nullable=False, comment='字（カナ）'),
    sa.Column('order', sa.Integer(), nullable=False, comment='並び順'),
    sa.Column('insu', sa.Integer(), nullable=False, comment='員数'),
    sa.Column('bosu', sa.Integer(), nullable=False, comment='母数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('tree_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_tree_table')
    op.drop_table('m_tori')
    op.drop_table('m_staff')
    op.drop_table('m_parts')
    op.drop_table('m_code_template')
    op.drop_table('m_code')
    # ### end Alembic commands ###
