"""create table

Revision ID: e8d97d5c6b00
Revises: 
Create Date: 2023-07-26 16:57:09.729124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d97d5c6b00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_code',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ckind', sa.Integer(), nullable=False),
    sa.Column('chead', sa.String(length=10), nullable=False),
    sa.Column('cenumber', sa.String(length=5), nullable=False),
    sa.Column('cnumber', sa.Integer(), nullable=False),
    sa.Column('cfoot', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('cid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_code')
    # ### end Alembic commands ###
