"""create table

Revision ID: 987ca4c0154f
Revises: e8d97d5c6b00
Create Date: 2023-07-26 17:24:08.336858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '987ca4c0154f'
down_revision = 'e8d97d5c6b00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_code_template',
    sa.Column('ctid', sa.Integer(), autoincrement=True, nullable=False, comment='テンプレートID'),
    sa.Column('ctkind', sa.Integer(), nullable=False, comment='種別'),
    sa.Column('cthead', sa.VARCHAR(length=10), nullable=False, comment='ヘッダ'),
    sa.Column('ctenumber', sa.VARCHAR(length=5), nullable=False, comment='英番号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('ctid')
    )
    op.alter_column('m_code', 'cid',
               existing_type=mysql.INTEGER(),
               comment='コードID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('m_code', 'ckind',
               existing_type=mysql.INTEGER(),
               comment='種別',
               existing_nullable=False)
    op.alter_column('m_code', 'chead',
               existing_type=mysql.VARCHAR(length=10),
               comment='ヘッダ',
               existing_nullable=False)
    op.alter_column('m_code', 'cenumber',
               existing_type=mysql.VARCHAR(length=5),
               comment='英番号',
               existing_nullable=False)
    op.alter_column('m_code', 'cnumber',
               existing_type=mysql.INTEGER(),
               comment='通番号',
               existing_nullable=False)
    op.alter_column('m_code', 'cfoot',
               existing_type=mysql.VARCHAR(length=10),
               comment='フッダー',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_code', 'cfoot',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='フッダー',
               existing_nullable=False)
    op.alter_column('m_code', 'cnumber',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='通番号',
               existing_nullable=False)
    op.alter_column('m_code', 'cenumber',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='英番号',
               existing_nullable=False)
    op.alter_column('m_code', 'chead',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='ヘッダ',
               existing_nullable=False)
    op.alter_column('m_code', 'ckind',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='種別',
               existing_nullable=False)
    op.alter_column('m_code', 'cid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='コードID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('m_code_template')
    # ### end Alembic commands ###
